# Generated by Django 5.2 on 2025-04-27 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RFC debe tener el formato correcto (13 caracteres).', regex='^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$')])),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')])),
                ('correo', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('contraseña', models.CharField(max_length=64)),
                ('sesion', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El CURP debe tener el formato correcto (18 caracteres).', regex='^[A-Z]{4}\\d{6}[A-Z]{6}\\d{2}$')])),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')])),
                ('noControl', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El número de control debe contener exactamente 9 dígitos.', regex='^\\d{9}$')])),
                ('correo', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('sexo', models.BooleanField()),
                ('fechaNacimiento', models.DateField()),
                ('carrera', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')])),
                ('titulado', models.BooleanField()),
                ('fechaEgreso', models.DateField()),
                ('contraseña', models.CharField(max_length=64)),
                ('sesion', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesSeleccionMultiple',
            fields=[
                ('idOpcion', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigoPregunta', models.CharField(max_length=5)),
                ('textoOpcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('folioEncuesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('lapso', models.CharField(max_length=9)),
                ('curp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.egresado')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoS4',
            fields=[
                ('folioAnexoS4', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta32', models.CharField(max_length=50)),
                ('pregunta33', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoS3',
            fields=[
                ('folioAnexoS3', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta29', models.CharField(max_length=50)),
                ('pregunta30', models.CharField(max_length=50)),
                ('pregunta31', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoS2',
            fields=[
                ('folioAnexoS2', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta27', models.CharField(max_length=50)),
                ('pregunta28', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoS1',
            fields=[
                ('folioAnexoS1', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta24', models.CharField(max_length=50)),
                ('pregunta25', models.CharField(max_length=50)),
                ('pregunta26', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaS1',
            fields=[
                ('folioEncuestaS1', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta1', models.CharField(max_length=50)),
                ('pregunta2', models.CharField(max_length=50)),
                ('pregunta3', models.CharField(max_length=50)),
                ('pregunta4', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaS2',
            fields=[
                ('folioEncuestaS2', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta5', models.CharField(max_length=50)),
                ('pregunta6', models.CharField(max_length=50)),
                ('pregunta7', models.CharField(max_length=50)),
                ('pregunta8', models.CharField(max_length=50)),
                ('pregunta9', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaS3',
            fields=[
                ('folioEncuestaS3', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta10', models.CharField(max_length=50)),
                ('pregunta11', models.CharField(max_length=50)),
                ('pregunta12', models.CharField(max_length=50)),
                ('pregunta13', models.CharField(max_length=50)),
                ('pregunta14', models.CharField(max_length=50)),
                ('pregunta15', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaS3Empresa',
            fields=[
                ('folioEncuestaS3Empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('giroEmpresa', models.CharField(max_length=50)),
                ('tamanoEmpresa', models.CharField(max_length=50)),
                ('areaTrabajo', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaS4',
            fields=[
                ('folioEncuestaS4', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta16', models.CharField(max_length=50)),
                ('pregunta17', models.CharField(max_length=50)),
                ('pregunta18', models.CharField(max_length=50)),
                ('pregunta19', models.CharField(max_length=50)),
                ('pregunta20', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaS5',
            fields=[
                ('folioEncuestaS5', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta21', models.CharField(max_length=50)),
                ('pregunta22', models.CharField(max_length=50)),
                ('pregunta23', models.CharField(max_length=50)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaSeleccionMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPregunta', models.CharField(max_length=5)),
                ('folioEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.encuesta')),
                ('idOpcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opcionesseleccionmultiple')),
            ],
            options={
                'unique_together': {('folioEncuesta', 'codigoPregunta')},
            },
        ),
    ]
