# Generated by Django 5.2 on 2025-05-03 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='carrera',
            field=models.CharField(blank=True, help_text='Si está vacío, el administrador tiene acceso a todas las carreras.', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
    ]
