# Generated by Django 5.2 on 2025-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
