# Generated by Django 5.2 on 2025-05-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_administrador_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
