# Generated by Django 5.2 on 2025-05-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_encuesta_fechafin'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='tempPwd',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
