# Generated by Django 5.2 on 2025-05-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_egresado_temppwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestas3',
            name='requisitosContratacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Competencias laborales'), (2, 'Titulo profesional'), (3, 'Examen de selección'), (4, 'Idioma extranjero'), (5, 'Actitudes y habilidades socio-comunicativas'), (6, 'Ninguno'), (7, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='requisitosContratacionOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='eficiencia',
            field=models.IntegerField(blank=True, choices=[(1, 'Muy eficiente'), (2, 'Eficiente'), (3, 'Poco eficiente'), (4, 'Deficiente')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='formacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Educativo'), (2, 'Turismo'), (3, 'Comercio'), (4, 'Servicios financieros'), (5, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='utilidad',
            field=models.IntegerField(blank=True, choices=[(1, 'Educativo'), (2, 'Turismo'), (3, 'Comercio'), (4, 'Servicios financieros'), (5, 'Otros')], null=True),
        ),
        migrations.AlterField(
            model_name='encuestas1',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Femenino'), (0, 'Masculino')], null=True),
        ),
    ]
