# Generated by Django 5.2 on 2025-05-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_egresado_token_verificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='token_verificacion',
        ),
    ]
