# Generated by Django 5.2 on 2025-05-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_encuestas3_requisitoscontratacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresadotemporal',
            name='fecha_creacion',
        ),
    ]
