# Generated by Django 5.2 on 2025-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_egresado_token_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
    ]
