# Generated by Django 5.2 on 2025-05-15 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_egresadotemporal_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresadotemporal',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
