# Generated by Django 5.2 on 2025-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_egresadotemporal_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos2',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Dirección/gerencia'), (2, 'Jefatura'), (3, 'Supervisión'), (4, 'Coordinador'), (5, 'Empleado'), (6, 'Dueño de empresa'), (7, 'Otras')], null=True),
        ),
    ]
