# Generated by Django 5.2 on 2025-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_anexos2_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexos1',
            name='razonNoTitulo',
            field=models.IntegerField(blank=True, choices=[(1, 'Compromiso laboral'), (2, 'Falta de tiempo'), (3, 'Falta de apoyo institucional'), (4, 'Otras')], null=True),
        ),
        migrations.AlterField(
            model_name='anexos2',
            name='medioTrabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Bolsa de trabajo del TecNM/ITVer'), (2, 'Anuncio en internet'), (3, 'Recomendación de colegas'), (4, 'Residencias profesionales'), (5, 'Otras')], null=True),
        ),
        migrations.AlterField(
            model_name='anexos2',
            name='razonNoTrabaja',
            field=models.IntegerField(blank=True, choices=[(1, 'Estudio un Posgrado'), (2, 'Por razones de salud'), (3, 'Ajustes propios de la empresa'), (4, 'No he encontrado un trabajo relacionado a lo que estudié'), (5, 'Otras')], null=True),
        ),
        migrations.AlterField(
            model_name='anexos3',
            name='aporte',
            field=models.IntegerField(blank=True, choices=[(1, 'Impartiendo un curso o conferencia'), (2, 'Apoyar para una visita industrial donde laboras'), (3, 'Apoyar para la realización de Residencias Profesionales'), (4, 'Apoyar para realizar investigaciones'), (5, 'Apoyar a jóvenes para la Educación Dual'), (6, 'Donativos'), (7, 'Otras')], null=True),
        ),
        migrations.AlterField(
            model_name='anexos4',
            name='documentos',
            field=models.IntegerField(choices=[(0, 'Manuales operativos'), (1, 'Procedimientos'), (2, 'Lineamientos'), (3, 'Informes técnicos'), (4, 'Otro')], null=True),
        ),
        migrations.AlterField(
            model_name='anexos4',
            name='etica',
            field=models.IntegerField(choices=[(1, 'Aplicar las normas básicas de una empresa'), (2, 'Aplicar reglas de cortesía que demuestran respeto por los demás'), (3, 'Asumir un comportamiento adecuado para la buena convivencia'), (4, 'Establecer una serie de normas como guía de conducta'), (5, 'Ninguna de las anteriores')], null=True),
        ),
        migrations.AlterField(
            model_name='anexos4',
            name='idiomas',
            field=models.IntegerField(choices=[(1, 'Inglés'), (2, 'Frances'), (3, 'Alemán'), (4, 'Italiano'), (5, 'Otras')], null=True),
        ),
        migrations.AlterField(
            model_name='encuestas3empresa',
            name='sectorPrimario',
            field=models.IntegerField(blank=True, choices=[(1, 'Agroindustrial'), (2, 'Pesquero'), (3, 'Minero'), (4, 'Otros')], null=True),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='areaCampoEstudio',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Área o campo de estudio'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='capacidadLiderazgo',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Capacidad de liderazgo'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='competenciaLaboral',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Competencia laboral'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='conocimientoIdiomas',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Conocimiento de idiomas'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='experienciaLaboral',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Experiencia laboral/práctica'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='formacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Excelente'), (2, 'Bueno'), (3, 'Regular'), (4, 'Malo'), (5, 'Pésimo')], null=True),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='otrosAspectos',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='personalidadActitudes',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Personalidad/actitudes'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='posicionamientoInstitucion',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Posicionamiento de la institución'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='recomendacionesReferencias',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Recomendaciones/referencias'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='titulacion',
            field=models.IntegerField(choices=[(1, '1(poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5(mucho)')], null=True, verbose_name='Titulación'),
        ),
        migrations.AlterField(
            model_name='encuestas4',
            name='utilidad',
            field=models.IntegerField(blank=True, choices=[(1, 'Excelente'), (2, 'Bueno'), (3, 'Regular'), (4, 'Malo'), (5, 'Pésimo')], null=True),
        ),
    ]
