# Generated by Django 5.2 on 2025-05-18 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_anexos1_razonnotitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='contraseña',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='fechaEgreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='noControl',
            field=models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de control debe contener exactamente 9 dígitos.', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='nombre',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='sexo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='titulado',
            field=models.BooleanField(null=True),
        ),
    ]
