# Generated by Django 5.2 on 2025-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_arreglar_campos_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorTemporal',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
