# Generated by Django 5.2 on 2025-05-18 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_egresado_contraseña_alter_egresado_fechaegreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')]),
        ),
    ]
