# Generated by Django 5.2 on 2025-05-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_administradortemporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresadoTemporal',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('no_control', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('sexo', models.BooleanField()),
                ('fecha_nacimiento', models.DateField()),
                ('carrera', models.CharField(max_length=100)),
                ('titulado', models.BooleanField()),
                ('fecha_egreso', models.DateField()),
                ('contraseña', models.CharField(max_length=128)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
