# Generated by Django 5.2 on 2025-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_egresado_correo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='anexos1',
            constraint=models.UniqueConstraint(fields=('folioEncuesta',), name='unique_folio_anexos1'),
        ),
        migrations.AddConstraint(
            model_name='anexos2',
            constraint=models.UniqueConstraint(fields=('folioEncuesta',), name='unique_folio_anexos2'),
        ),
        migrations.AddConstraint(
            model_name='anexos3',
            constraint=models.UniqueConstraint(fields=('folioEncuesta',), name='unique_folio_anexos3'),
        ),
        migrations.AddConstraint(
            model_name='anexos4',
            constraint=models.UniqueConstraint(fields=('folioEncuesta',), name='unique_folio_anexos4'),
        ),
    ]
