# Generated by Django 5.2 on 2025-05-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_egresadotemporal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionesseleccionmultiple',
            options={'ordering': ['codigoPregunta', 'valorNumerico']},
        ),
        migrations.RemoveField(
            model_name='anexos1',
            name='pregunta24',
        ),
        migrations.RemoveField(
            model_name='anexos1',
            name='pregunta25',
        ),
        migrations.RemoveField(
            model_name='anexos1',
            name='pregunta26',
        ),
        migrations.RemoveField(
            model_name='anexos2',
            name='pregunta27',
        ),
        migrations.RemoveField(
            model_name='anexos2',
            name='pregunta28',
        ),
        migrations.RemoveField(
            model_name='anexos3',
            name='pregunta29',
        ),
        migrations.RemoveField(
            model_name='anexos3',
            name='pregunta30',
        ),
        migrations.RemoveField(
            model_name='anexos3',
            name='pregunta31',
        ),
        migrations.RemoveField(
            model_name='anexos4',
            name='pregunta32',
        ),
        migrations.RemoveField(
            model_name='anexos4',
            name='pregunta33',
        ),
        migrations.RemoveField(
            model_name='encuestas1',
            name='pregunta1',
        ),
        migrations.RemoveField(
            model_name='encuestas1',
            name='pregunta2',
        ),
        migrations.RemoveField(
            model_name='encuestas1',
            name='pregunta3',
        ),
        migrations.RemoveField(
            model_name='encuestas1',
            name='pregunta4',
        ),
        migrations.RemoveField(
            model_name='encuestas2',
            name='pregunta5',
        ),
        migrations.RemoveField(
            model_name='encuestas2',
            name='pregunta6',
        ),
        migrations.RemoveField(
            model_name='encuestas2',
            name='pregunta7',
        ),
        migrations.RemoveField(
            model_name='encuestas2',
            name='pregunta8',
        ),
        migrations.RemoveField(
            model_name='encuestas2',
            name='pregunta9',
        ),
        migrations.RemoveField(
            model_name='encuestas3',
            name='pregunta10',
        ),
        migrations.RemoveField(
            model_name='encuestas3',
            name='pregunta11',
        ),
        migrations.RemoveField(
            model_name='encuestas3',
            name='pregunta12',
        ),
        migrations.RemoveField(
            model_name='encuestas3',
            name='pregunta13',
        ),
        migrations.RemoveField(
            model_name='encuestas3',
            name='pregunta14',
        ),
        migrations.RemoveField(
            model_name='encuestas3',
            name='pregunta15',
        ),
        migrations.RemoveField(
            model_name='encuestas3empresa',
            name='areaTrabajo',
        ),
        migrations.RemoveField(
            model_name='encuestas3empresa',
            name='giroEmpresa',
        ),
        migrations.RemoveField(
            model_name='encuestas3empresa',
            name='nombreEmpresa',
        ),
        migrations.RemoveField(
            model_name='encuestas4',
            name='pregunta16',
        ),
        migrations.RemoveField(
            model_name='encuestas4',
            name='pregunta17',
        ),
        migrations.RemoveField(
            model_name='encuestas4',
            name='pregunta18',
        ),
        migrations.RemoveField(
            model_name='encuestas4',
            name='pregunta19',
        ),
        migrations.RemoveField(
            model_name='encuestas4',
            name='pregunta20',
        ),
        migrations.RemoveField(
            model_name='encuestas5',
            name='pregunta21',
        ),
        migrations.RemoveField(
            model_name='encuestas5',
            name='pregunta22',
        ),
        migrations.RemoveField(
            model_name='encuestas5',
            name='pregunta23',
        ),
        migrations.AlterUniqueTogether(
            name='respuestaseleccionmultiple',
            unique_together={('folioEncuesta', 'opcion')},
        ),
        migrations.AddField(
            model_name='anexos1',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='fechaEgreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='nombreCompleto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='razonNoTitulo',
            field=models.IntegerField(blank=True, choices=[(1, 'Compromiso Laboral'), (2, 'Falta de Tiempo'), (3, 'Falta de Apoyo Institucional'), (4, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='razonNoTituloOtra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='redesSociales',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='anexos1',
            name='titulado',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='antiguedad',
            field=models.IntegerField(blank=True, choices=[(1, '0-3 Meses'), (2, '4-6 Meses'), (3, '6 Meses - 1 Año'), (4, '1-5 Años'), (5, '6 años o más')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='area',
            field=models.IntegerField(blank=True, choices=[(1, 'Producción'), (2, 'Ambiental'), (3, 'Seguridad'), (4, 'Recursos Financiero'), (5, 'Mantenimiento'), (6, 'Recursos Humanos'), (7, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='areaOtra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='medioTrabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Bolsa de trabajo del TecNM/ITVer'), (2, 'Anuncio en internet'), (3, 'Recomendación de colegas'), (4, 'Residencias profesional'), (5, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='medioTrabajoOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='razonNoConseguirTrabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='razonNoTrabaja',
            field=models.IntegerField(blank=True, choices=[(1, 'Estudio un posgrado'), (2, 'Por razones de salud'), (3, 'Ajustes propios de la empresa'), (4, 'No he encontrado un trabajo relacionado a lo que estudié'), (5, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='razonNoTrabajaOtra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='relacionTrabajoCarrera',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Dirección, gerencia'), (2, 'Jefatura'), (3, 'Supervisión'), (4, 'Coordinador'), (5, 'Empleado'), (6, 'Dueño de empresa'), (7, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='rolOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='satisfaccion',
            field=models.IntegerField(blank=True, choices=[(1, 'Muy satisfecho'), (2, 'Satisfecho'), (3, 'Poco satisfecho'), (4, 'Insatisfecho')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='sector',
            field=models.IntegerField(blank=True, choices=[(1, 'Sector privado'), (2, 'Sector público'), (3, 'En empresa propia'), (4, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='sectorOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='tiempoTrabajoRelacionado',
            field=models.IntegerField(blank=True, choices=[(1, 'Al egresar ya contaba con un trabajo'), (2, 'Menos de 6 meses'), (3, 'Más de 1 año'), (4, 'Aún no lo consigo')], null=True),
        ),
        migrations.AddField(
            model_name='anexos2',
            name='trabaja',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='aporte',
            field=models.IntegerField(blank=True, choices=[(1, 'Impartiendo un curso o conferencia'), (2, 'Apoyar para una visita industrial donde laboras'), (3, 'Apoyar a jóvenes de la Institución para realización de Residencias Profesionales'), (4, 'Apoyar a jóvenes para realizar investigaciones'), (5, 'Apoyar a jóvenes para realizar Educación Dual'), (6, 'Donativos en especie'), (7, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='aporteOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='competencias',
            field=models.IntegerField(choices=[(1, 'Totalmente'), (2, 'Suficiente'), (3, 'Poco'), (4, 'Nada')], null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='contacto',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='educativo',
            field=models.IntegerField(choices=[(1, 'Manejo de softwares'), (2, 'Manejo de normas nacionales e internacionales'), (3, 'Evaluación de proyectos de inversión'), (4, 'Habilidades directivas'), (5, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='educativoOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='participar',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos3',
            name='satisfaccion',
            field=models.IntegerField(choices=[(1, 'Muy Satisfecho'), (2, 'Satisfecho'), (3, 'Poco Satisfecho'), (4, 'Insatisfecho')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='asociacion',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='asociacionEspecifique',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='calidad',
            field=models.IntegerField(choices=[(0, 'Calidad'), (1, 'Ambiental'), (2, 'Seguridad'), (3, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='calidadOtra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='certificacion',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='certificacionCuales',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='colabora',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='documentos',
            field=models.IntegerField(choices=[(0, 'Manuales operativos'), (1, 'Procedimientos'), (2, 'Lineamientos'), (3, 'Informes Técnicos'), (4, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='documentosOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='etica',
            field=models.IntegerField(choices=[(1, 'Aplicar las Normas básicas de una empresa'), (2, 'Aplicar reglas de cortesía que demuestran respeto por los demás'), (3, 'Asumir un comportamiento adecuado para la buena convivencia'), (4, 'Establecer una serie de normas como guía de conducta'), (5, 'Ninguna de las anteriores')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='herramientas',
            field=models.IntegerField(choices=[(1, 'Documentos técnicos'), (2, 'Planos de ingeniería'), (3, 'Softwares'), (4, 'Normas nacionales o internacionales'), (5, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='herramientasOtra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='idiomas',
            field=models.IntegerField(choices=[(1, 'Inglés'), (2, 'Frances'), (3, 'Alemán'), (4, 'Italiano'), (5, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='idiomasOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='participaRedes',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='publicacion',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='publicacionEspecifique',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='servicios',
            field=models.IntegerField(choices=[(1, 'Asesoría o consultoría'), (2, 'Peritaje'), (3, 'Certificación'), (4, 'Ninguno'), (5, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='serviciosOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='tipoInvestigacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Aplicada'), (2, 'Experimental'), (3, 'Documental'), (4, 'Descriptiva'), (5, 'Otras')], null=True),
        ),
        migrations.AddField(
            model_name='anexos4',
            name='tipoInvestigacionOtra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='carrera',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='cp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='curp',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='domicilio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='dominioIngles',
            field=models.IntegerField(help_text='Porcentaje de dominio', null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='especialidad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='especificarPaquetes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='estadoCivil',
            field=models.IntegerField(choices=[(1, 'Soltero'), (2, 'Casado')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='fechaEgreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='manejoPaquetes',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='noControl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='otroIdioma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Femenino'), (2, 'Masculino')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='encuestas1',
            name='titulado',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas2',
            name='calidadDocentes',
            field=models.IntegerField(choices=[(4, 'Muy buena'), (3, 'Buena'), (2, 'Regular'), (1, 'Mala')], null=True, verbose_name='Calidad de docentes'),
        ),
        migrations.AddField(
            model_name='encuestas2',
            name='enfasisInvestigacion',
            field=models.IntegerField(choices=[(4, 'Muy buena'), (3, 'Buena'), (2, 'Regular'), (1, 'Mala')], null=True, verbose_name='Énfasis que se le prestaba a la investigación dentro del proceso de enseñanza'),
        ),
        migrations.AddField(
            model_name='encuestas2',
            name='experienciaResidencia',
            field=models.IntegerField(choices=[(4, 'Muy buena'), (3, 'Buena'), (2, 'Regular'), (1, 'Mala')], null=True, verbose_name='Experiencia obtenida a través de la residencia profesional'),
        ),
        migrations.AddField(
            model_name='encuestas2',
            name='oportunidadesProyectos',
            field=models.IntegerField(choices=[(4, 'Muy buena'), (3, 'Buena'), (2, 'Regular'), (1, 'Mala')], null=True, verbose_name='Oportunidades de participar en proyectos de investigación y desarrollo'),
        ),
        migrations.AddField(
            model_name='encuestas2',
            name='planEstudios',
            field=models.IntegerField(choices=[(4, 'Muy buena'), (3, 'Buena'), (2, 'Regular'), (1, 'Mala')], null=True, verbose_name='Plan de estudios'),
        ),
        migrations.AddField(
            model_name='encuestas2',
            name='satisfaccionCondiciones',
            field=models.IntegerField(choices=[(4, 'Muy buena'), (3, 'Buena'), (2, 'Regular'), (1, 'Mala')], null=True, verbose_name='Satisfacción con las condiciones de estudio'),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='actividad',
            field=models.IntegerField(choices=[(1, 'Trabaja'), (2, 'Estudia'), (3, 'Estudia y trabaja'), (4, 'No estudia ni trabaja')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='anioIngreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='antiguedad',
            field=models.IntegerField(blank=True, choices=[(1, 'Menos de un año'), (2, 'Un año'), (3, 'Dos años'), (4, 'Tres años'), (5, 'Más de tres años')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='condicionTrabajo',
            field=models.IntegerField(blank=True, choices=[(1, 'Base'), (2, 'Eventual'), (3, 'Contrato'), (4, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='condicionTrabajoOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='escribirPorcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='escucharPorcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='especialidadInstitucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='hablarPorcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='idiomaUtiliza',
            field=models.IntegerField(blank=True, choices=[(1, 'Inglés'), (2, 'Francés'), (3, 'Alemán'), (4, 'Japones'), (5, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='idiomaUtilizaOtro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='ingreso',
            field=models.IntegerField(blank=True, choices=[(1, 'Menos de cinco'), (2, 'Entre cinco y siete'), (3, 'Entre ocho y diez'), (4, 'Más de diez')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='leerPorcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='medioEmpleo',
            field=models.IntegerField(blank=True, choices=[(1, 'Bolsa de trabajo del plantel'), (2, 'Contactos personales'), (3, 'Residencia Profesional'), (4, 'Medios masivos de comunicación'), (5, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='medioEmpleoOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='nivelJerarquico',
            field=models.IntegerField(blank=True, choices=[(1, 'Técnico'), (2, 'Supervisor'), (3, 'Jefe de área'), (4, 'Funcionario'), (5, 'Directivo'), (6, 'Empresario')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='relacionTrabajo',
            field=models.IntegerField(blank=True, choices=[(1, '0%'), (2, '20%'), (3, '40%'), (4, '60%'), (5, '80%'), (6, '100%')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='tiempoObtenerEmpleo',
            field=models.IntegerField(blank=True, choices=[(1, 'Antes de Egresar'), (2, 'Menos de seis meses'), (3, 'Entre seis meses y un año'), (4, 'Más de un año')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='tipoEstudio',
            field=models.IntegerField(blank=True, choices=[(1, 'Especialidad'), (2, 'Maestría'), (3, 'Doctorado'), (4, 'Idiomas'), (5, 'Otra')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3',
            name='tipoEstudioOtro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='cp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='domicilio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='giroActividad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='nombreJefeInmediato',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='puestoJefeInmediato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='razonSocial',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='sectorPrimario',
            field=models.IntegerField(blank=True, choices=[(1, 'Agroindustria'), (2, 'Pesquero'), (3, 'Minero'), (4, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='sectorPrimarioOtro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='sectorSecundario',
            field=models.IntegerField(blank=True, choices=[(1, 'Industrial'), (2, 'Construcción'), (3, 'Petrolero'), (4, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='sectorSecundarioOtro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='sectorTerciario',
            field=models.IntegerField(blank=True, choices=[(1, 'Educativo'), (2, 'Turismo'), (3, 'Comercio'), (4, 'Servicios financieros'), (5, 'Otros')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='sectorTerciarioOtro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='encuestas3empresa',
            name='tipoOrganismo',
            field=models.IntegerField(choices=[(1, 'Público'), (2, 'Privado'), (3, 'Social')], null=True),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='areaCampoEstudio',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Área o campo de estudio'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='capacidadLiderazgo',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Capacidad de liderazgo'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='competenciaLaboral',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Competencia laboral'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='conocimientoIdiomas',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Conocimiento de idiomas'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='experienciaLaboral',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Experiencia laboral/práctica'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='otrosAspectos',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Otros'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='personalidadActitudes',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Personalidad/actitudes'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='posicionamientoInstitucion',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Posicionamiento de la institución'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='recomendacionesReferencias',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Recomendaciones/referencias'),
        ),
        migrations.AddField(
            model_name='encuestas4',
            name='titulacion',
            field=models.IntegerField(choices=[(1, '1 (poco)'), (2, '2'), (3, '3'), (4, '4'), (5, '5 (mucho)')], null=True, verbose_name='Titulación'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='comentariosSugerencias',
            field=models.TextField(blank=True, null=True, verbose_name='Opinión o recomendación para mejorar la formación profesional de un egresado de su carrera'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='cursosActualizacion',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True, verbose_name='Le gustaría tomar cursos de actualización'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='cursosActualizacionCuales',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Qué cursos de actualización le gustaría tomar?'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='organismosProfesionistasCuales',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿A cuáles organismos de profesionistas pertenece?'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='organizacionesSocialesCuales',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿A cuáles organizaciones sociales pertenece?'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='perteneceAsociacionEgresados',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True, verbose_name='Pertenece a la asociación de egresados'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='perteneceOrganismosProfesionistas',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True, verbose_name='Pertenece a organismos de profesionistas'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='perteneceOrganizacionesSociales',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True, verbose_name='Pertenece a organizaciones sociales'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='tomarPosgrado',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], null=True, verbose_name='Le gustaría tomar algún Posgrado'),
        ),
        migrations.AddField(
            model_name='encuestas5',
            name='tomarPosgradoCual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Qué posgrado le gustaría tomar?'),
        ),
        migrations.AddField(
            model_name='opcionesseleccionmultiple',
            name='valorNumerico',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='respuestaseleccionmultiple',
            name='opcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.opcionesseleccionmultiple'),
        ),
        migrations.AlterField(
            model_name='encuestas3empresa',
            name='tamanoEmpresa',
            field=models.IntegerField(choices=[(1, 'Microempresa (1-30)'), (2, 'Pequeña (31-100)'), (3, 'Mediana (101-500)'), (4, 'Grande (más de 500)')], null=True),
        ),
        migrations.AlterField(
            model_name='opcionesseleccionmultiple',
            name='codigoPregunta',
            field=models.CharField(choices=[('III.4', 'Requisitos de contratación'), ('III.5', 'Idioma que utiliza en su trabajo')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='opcionesseleccionmultiple',
            name='textoOpcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaseleccionmultiple',
            name='folioEncuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.encuesta'),
        ),
        migrations.AlterField(
            model_name='respuestaseleccionmultiple',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='respuestaseleccionmultiple',
            name='codigoPregunta',
        ),
        migrations.RemoveField(
            model_name='respuestaseleccionmultiple',
            name='idOpcion',
        ),
    ]
