# Generated by Django 5.2 on 2025-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_anexos1_unique_folio_anexos1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEncuestaCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
